theme: jekyll-theme-minimal
title: PyProject
description: This is a personal project which stores various snippets of python that I am working on. Bookmark this to keep updated.
email: denis_jackman@hotmail.com





