name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -i https://test.pypi.org/simple/ djgamemodule
        pip install flake8
    - name: Pylint Lint Analysis
      run: |
        pylint --rcfile=pylint.rc $(git ls-files '*.py')
    - name: Flake8 Lint Analysis
      run: |
        flake8 --config flake8.cfg --exit-zero $(git ls-files '*.py')